---
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Copy zabbix-agent basic configuration.
  template:
    src: zabbix-agent.j2
    dest: "/etc/zabbix/zabbix_agentd.conf"
    owner: root
    group: root
    mode: 0644
    force: yes
  notify: restart zabbix-agent

- name: Copy zabbix-agent hypervisor configuration.
  copy:
    src: zabbix-agent-hv.conf
    dest: "/etc/zabbix/zabbix_agentd.conf.d/zabbix-agent-hv.conf"
    owner: root
    group: root
    mode: 0644
    force: yes
    backup: yes
  notify: restart zabbix-agent
  when: inventory_hostname in groups['hypervisors']

- name: copy pg sql scripts
  copy:
    src: "{{ item }}"
    dest: /var/lib/zabbix/postgresql/
  with_fileglob:
    - files/pg/*
  when: inventory_hostname in groups['db']

- name: Copy zabbix-agent db configuration.
  copy:
    src: zabbix-agent-db-psql.conf
    dest: "/etc/zabbix/zabbix_agentd.conf.d/postgresql.conf"
    owner: root
    group: root
    mode: 0644
    force: yes
    backup: yes
  notify: restart zabbix-agent
  when: inventory_hostname in groups['db']

- name: Copy zabbix-agent proxy configuration.
  copy:
    src: zabbix-agent-db-mysql.conf
    dest: "/etc/zabbix/zabbix_agentd.d/mysql.conf"
    owner: root
    group: root
    mode: 0644
    force: yes
    backup: yes
  notify: restart zabbix-agent
  when: inventory_hostname in groups['proxy']

- name: Ensure Zabbix-agent is started and enabled at boot.
  service:
    name: zabbix-agent
    state: started
    enabled: true
