---
- name: Ensure required dependencies are present.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Install zabbix-agent
  package: name=zabbix-agent state=present

