---
- name: install zabbix.rpm from a local file
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    state: present

- name: Creates directory zabbix log RedHat
  file:
    path: /var/log/zabbix-agent
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0755
    recurse: yes

- name: Install zabbix-agent
  package: name=zabbix-agent state=present

- name: Creates directory RedHat
  file:
    path: /etc/zabbix/zabbix_agentd.conf.d
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0644
    recurse: yes

- name: Del setup zabbix log directory
  file:
    state: absent
    path: /var/log/zabbix

